spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:${DB_CONNECTION}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  security:
    basic:
      enabled: true
      realm: some-service
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

server:
  servlet:
    context-path: /api/v1/bookshelf
  port: ${API_PORT}

