spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  security:
    basic:
      enabled: true
      realm: some-service
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

server:
  port: ${API_PORT}

